// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: server-center.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protocol {

  /// <summary>Holder for reflection information generated from server-center.proto</summary>
  public static partial class ServerCenterReflection {

    #region Descriptor
    /// <summary>File descriptor for server-center.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServerCenterReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNzZXJ2ZXItY2VudGVyLnByb3RvEghwcm90b2NvbBoUY2xpZW50LWFjY291",
            "bnQucHJvdG8aEWNsaWVudC1jaGF0LnByb3RvGhFjbGllbnQtZ2FtZS5wcm90",
            "bxoRY2xpZW50LXJvb20ucHJvdG8aDGhlYWRlci5wcm90bxoLdW5pdHkucHJv",
            "dG8iSwoMRW50ZXJHYW1lUmVwEgsKA3VpZBgBIAEoAxIOCgZyb29tSWQYAiAB",
            "KAMSDgoGZ2FtZUlkGAMgASgDEg4KBmdhbWVJcBgEIAEoCSIaCgtSZUNvbm5l",
            "Y1JlcRILCgN1aWQYASABKAMy9wYKEkNlbnRlcjRHYXRlU2VydmljZRIxCgVM",
            "b2dpbhISLnByb3RvY29sLkxvZ2luUmVxGhIucHJvdG9jb2wuTG9naW5BY2si",
            "ABI0CgZMb2dvdXQSEy5wcm90b2NvbC5Mb2dvdXRSZXEaEy5wcm90b2NvbC5M",
            "b2dvdXRBY2siABI3CglSZUNvbm5lY3QSFS5wcm90b2NvbC5SZUNvbm5lY1Jl",
            "cRoRLnByb3RvY29sLkNhbGxBY2siABI2CghLaWNrVXNlchIVLnByb3RvY29s",
            "LktpY2tVc2VyUmVxGhEucHJvdG9jb2wuQ2FsbEFjayIAEkAKCkNyZWF0ZVJv",
            "b20SFy5wcm90b2NvbC5DcmVhdGVSb29tUmVxGhcucHJvdG9jb2wuQ3JlYXRl",
            "Um9vbUFjayIAEjoKCEpvaW5Sb29tEhUucHJvdG9jb2wuSm9pblJvb21SZXEa",
            "FS5wcm90b2NvbC5Kb2luUm9vbUFjayIAEjoKCEV4aXRSb29tEhUucHJvdG9j",
            "b2wuRXhpdFJvb21SZXEaFS5wcm90b2NvbC5FeGl0Um9vbUFjayIAEkMKC0Rp",
            "c2NhcmRSb29tEhgucHJvdG9jb2wuRGlzY2FyZFJvb21SZXEaGC5wcm90b2Nv",
            "bC5EaXNjYXJkUm9vbUFjayIAElsKE0dldEdhbWVSb29tVHlwZUxpc3QSIC5w",
            "cm90b2NvbC5HZXRHYW1lUm9vbVR5cGVMaXN0UmVxGiAucHJvdG9jb2wuR2V0",
            "R2FtZVJvb21UeXBlTGlzdEFjayIAEj0KCUVudGVyR2FtZRIWLnByb3RvY29s",
            "LkVudGVyR2FtZVJlcRoWLnByb3RvY29sLkVudGVyR2FtZVJlcCIAEjoKCEV4",
            "aXRHYW1lEhUucHJvdG9jb2wuRXhpdEdhbWVSZXEaFS5wcm90b2NvbC5FeGl0",
            "R2FtZUFjayIAEjoKClNlbmRUb1VzZXISFy5wcm90b2NvbC5TZW5kVG9Vc2Vy",
            "UmVxGhEucHJvdG9jb2wuQ2FsbEFjayIAEjoKClNlbmRUb1Jvb20SFy5wcm90",
            "b2NvbC5TZW5kVG9Sb29tUmVxGhEucHJvdG9jb2wuQ2FsbEFjayIAEjgKCUJv",
            "YXJkY2FzdBIWLnByb3RvY29sLkJvYXJkY2FzdFJlcRoRLnByb3RvY29sLkNh",
            "bGxBY2siADJMChJDZW50ZXI0R2FtZVNlcnZpY2USNgoIS2lja1VzZXISFS5w",
            "cm90b2NvbC5LaWNrVXNlclJlcRoRLnByb3RvY29sLkNhbGxBY2siAGIGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Protocol.ClientAccountReflection.Descriptor, global::Protocol.ClientChatReflection.Descriptor, global::Protocol.ClientGameReflection.Descriptor, global::Protocol.ClientRoomReflection.Descriptor, global::Protocol.HeaderReflection.Descriptor, global::Protocol.UnityReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Protocol.EnterGameRep), global::Protocol.EnterGameRep.Parser, new[]{ "Uid", "RoomId", "GameId", "GameIp" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protocol.ReConnecReq), global::Protocol.ReConnecReq.Parser, new[]{ "Uid" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class EnterGameRep : pb::IMessage<EnterGameRep> {
    private static readonly pb::MessageParser<EnterGameRep> _parser = new pb::MessageParser<EnterGameRep>(() => new EnterGameRep());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EnterGameRep> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protocol.ServerCenterReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EnterGameRep() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EnterGameRep(EnterGameRep other) : this() {
      uid_ = other.uid_;
      roomId_ = other.roomId_;
      gameId_ = other.gameId_;
      gameIp_ = other.gameIp_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EnterGameRep Clone() {
      return new EnterGameRep(this);
    }

    /// <summary>Field number for the "uid" field.</summary>
    public const int UidFieldNumber = 1;
    private long uid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Uid {
      get { return uid_; }
      set {
        uid_ = value;
      }
    }

    /// <summary>Field number for the "roomId" field.</summary>
    public const int RoomIdFieldNumber = 2;
    private long roomId_;
    /// <summary>
    ///房间号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long RoomId {
      get { return roomId_; }
      set {
        roomId_ = value;
      }
    }

    /// <summary>Field number for the "gameId" field.</summary>
    public const int GameIdFieldNumber = 3;
    private long gameId_;
    /// <summary>
    ///游戏id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long GameId {
      get { return gameId_; }
      set {
        gameId_ = value;
      }
    }

    /// <summary>Field number for the "gameIp" field.</summary>
    public const int GameIpFieldNumber = 4;
    private string gameIp_ = "";
    /// <summary>
    ///game服务器
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string GameIp {
      get { return gameIp_; }
      set {
        gameIp_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EnterGameRep);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EnterGameRep other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Uid != other.Uid) return false;
      if (RoomId != other.RoomId) return false;
      if (GameId != other.GameId) return false;
      if (GameIp != other.GameIp) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Uid != 0L) hash ^= Uid.GetHashCode();
      if (RoomId != 0L) hash ^= RoomId.GetHashCode();
      if (GameId != 0L) hash ^= GameId.GetHashCode();
      if (GameIp.Length != 0) hash ^= GameIp.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Uid != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Uid);
      }
      if (RoomId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(RoomId);
      }
      if (GameId != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(GameId);
      }
      if (GameIp.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(GameIp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Uid != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Uid);
      }
      if (RoomId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(RoomId);
      }
      if (GameId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(GameId);
      }
      if (GameIp.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GameIp);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EnterGameRep other) {
      if (other == null) {
        return;
      }
      if (other.Uid != 0L) {
        Uid = other.Uid;
      }
      if (other.RoomId != 0L) {
        RoomId = other.RoomId;
      }
      if (other.GameId != 0L) {
        GameId = other.GameId;
      }
      if (other.GameIp.Length != 0) {
        GameIp = other.GameIp;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Uid = input.ReadInt64();
            break;
          }
          case 16: {
            RoomId = input.ReadInt64();
            break;
          }
          case 24: {
            GameId = input.ReadInt64();
            break;
          }
          case 34: {
            GameIp = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class ReConnecReq : pb::IMessage<ReConnecReq> {
    private static readonly pb::MessageParser<ReConnecReq> _parser = new pb::MessageParser<ReConnecReq>(() => new ReConnecReq());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ReConnecReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protocol.ServerCenterReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReConnecReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReConnecReq(ReConnecReq other) : this() {
      uid_ = other.uid_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReConnecReq Clone() {
      return new ReConnecReq(this);
    }

    /// <summary>Field number for the "uid" field.</summary>
    public const int UidFieldNumber = 1;
    private long uid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Uid {
      get { return uid_; }
      set {
        uid_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ReConnecReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ReConnecReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Uid != other.Uid) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Uid != 0L) hash ^= Uid.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Uid != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Uid);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Uid != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Uid);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ReConnecReq other) {
      if (other == null) {
        return;
      }
      if (other.Uid != 0L) {
        Uid = other.Uid;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Uid = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
