// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: server-gate.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protocol {

  /// <summary>Holder for reflection information generated from server-gate.proto</summary>
  public static partial class ServerGateReflection {

    #region Descriptor
    /// <summary>File descriptor for server-gate.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServerGateReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFzZXJ2ZXItZ2F0ZS5wcm90bxIIcHJvdG9jb2waC3VuaXR5LnByb3RvGgxo",
            "ZWFkZXIucHJvdG8yRQoLR2F0ZVNlcnZpY2USNgoIS2lja1VzZXISFS5wcm90",
            "b2NvbC5LaWNrVXNlclJlcRoRLnByb3RvY29sLkNhbGxBY2siAGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Protocol.UnityReflection.Descriptor, global::Protocol.HeaderReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
